### ISSUE TITLE
Nemesis(.clangd setting sample)

### ISSUE THREAD

**Issue by SARDONYX-sard** [SARDONYX-forks/Project-New-Reign---Nemesis-Main#4]
```yaml
CompileFlags: # Tweak the parse settings
  Add: # treat all files as C++, enable more warnings
    - -Wall
    - -Werror
    - -Wextra
    - -pedantic
    - "-IE:/GAME/Project-New-Reign---Nemesis-Main/build/5.15.2/msvc2019/include"
    - "-IE:/GAME/Project-New-Reign---Nemesis-Main/build/_deps/boost-src/boost/include"
    - "-IE:/GAME/Project-New-Reign---Nemesis-Main/build/_deps/cpython-src/include"
    - "-IE:/GAME/Project-New-Reign---Nemesis-Main/include"
  Remove:
    - -W* # strip all other warning-related flags
  # Compiler: cl # Change argv[0] of compile flags to `clang++`

Diagnostics:
  ClangTidy:
    Add: modernize*
    Remove: modernize-use-trailing-return-type
```
